//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenpaiCreationKit.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SenpaiCreationKit.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hinzufügen ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die alle ähnelt.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Senpai Creation Kit ツ ähnelt.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abbrechen ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die erstellen abbrechen ähnelt.
        /// </summary>
        public static string CancelCreation {
            get {
                return ResourceManager.GetString("CancelCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bearbeiten abbrechen ähnelt.
        /// </summary>
        public static string CancelEdit {
            get {
                return ResourceManager.GetString("CancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die auswählen ähnelt.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle auswählen ähnelt.
        /// </summary>
        public static string ChooseAll {
            get {
                return ResourceManager.GetString("ChooseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die erstellen ähnelt.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flashcardslektion erstellen ähnelt.
        /// </summary>
        public static string CreateFlashLesson {
            get {
                return ResourceManager.GetString("CreateFlashLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insertlektion erstellen ähnelt.
        /// </summary>
        public static string CreateInsertLesson {
            get {
                return ResourceManager.GetString("CreateInsertLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektion erstellen ähnelt.
        /// </summary>
        public static string CreateLesson {
            get {
                return ResourceManager.GetString("CreateLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vokabellektion erstellen ähnelt.
        /// </summary>
        public static string CreateVocabLesson {
            get {
                return ResourceManager.GetString("CreateVocabLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Source=SenpaiDatabase.sdf ähnelt.
        /// </summary>
        public static string dbConnection {
            get {
                return ResourceManager.GetString("dbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die löschen ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Texte löschen ähnelt.
        /// </summary>
        public static string DeleteClozes {
            get {
                return ResourceManager.GetString("DeleteClozes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanjis löschen ähnelt.
        /// </summary>
        public static string DeleteKanjis {
            get {
                return ResourceManager.GetString("DeleteKanjis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen löschen ähnelt.
        /// </summary>
        public static string DeleteLesson {
            get {
                return ResourceManager.GetString("DeleteLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen löschen ähnelt.
        /// </summary>
        public static string DeleteLessons {
            get {
                return ResourceManager.GetString("DeleteLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vokabeln löschen ähnelt.
        /// </summary>
        public static string DeleteWords {
            get {
                return ResourceManager.GetString("DeleteWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detail Ansicht ähnelt.
        /// </summary>
        public static string DetailView {
            get {
                return ResourceManager.GetString("DetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektion bearbeiten ähnelt.
        /// </summary>
        public static string EditLesson {
            get {
                return ResourceManager.GetString("EditLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beispiel-Kanji ähnelt.
        /// </summary>
        public static string Example1 {
            get {
                return ResourceManager.GetString("Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beispiel-Kana ähnelt.
        /// </summary>
        public static string Example2 {
            get {
                return ResourceManager.GetString("Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beispiel-Übersetzung ähnelt.
        /// </summary>
        public static string Example3 {
            get {
                return ResourceManager.GetString("Example3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen exportieren ähnelt.
        /// </summary>
        public static string ExportLesson {
            get {
                return ResourceManager.GetString("ExportLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen filtern ähnelt.
        /// </summary>
        public static string FilterLessons {
            get {
                return ResourceManager.GetString("FilterLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter filtern ähnelt.
        /// </summary>
        public static string FilterWords {
            get {
                return ResourceManager.GetString("FilterWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flashcards-Lektionen ähnelt.
        /// </summary>
        public static string FlashLesson {
            get {
                return ResourceManager.GetString("FlashLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweise ähnelt.
        /// </summary>
        public static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen importieren ähnelt.
        /// </summary>
        public static string ImportLesson {
            get {
                return ResourceManager.GetString("ImportLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lückentext-Lektionen ähnelt.
        /// </summary>
        public static string InsertLesson {
            get {
                return ResourceManager.GetString("InsertLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lückentextstellen auswählen ähnelt.
        /// </summary>
        public static string InsertParts {
            get {
                return ResourceManager.GetString("InsertParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kana ähnelt.
        /// </summary>
        public static string Kana {
            get {
                return ResourceManager.GetString("Kana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanji ähnelt.
        /// </summary>
        public static string Kanji {
            get {
                return ResourceManager.GetString("Kanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanji-, Bedeutung- und Onyomi-Textboxen dürfen nicht leer sein! ähnelt.
        /// </summary>
        public static string KanjiTextboxesCantBeEmpty {
            get {
                return ResourceManager.GetString("KanjiTextboxesCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunyomi Lesung ähnelt.
        /// </summary>
        public static string Kunyomi {
            get {
                return ResourceManager.GetString("Kunyomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionsname ähnelt.
        /// </summary>
        public static string LessonName {
            get {
                return ResourceManager.GetString("LessonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionsname darf nicht leer sein! ähnelt.
        /// </summary>
        public static string LessonNameEmpty {
            get {
                return ResourceManager.GetString("LessonNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen ähnelt.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marktplatz ähnelt.
        /// </summary>
        public static string MarketPlace {
            get {
                return ResourceManager.GetString("MarketPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bedeutung ähnelt.
        /// </summary>
        public static string Meaning {
            get {
                return ResourceManager.GetString("Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Onyomi Lesung ähnelt.
        /// </summary>
        public static string Onyomi {
            get {
                return ResourceManager.GetString("Onyomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wirklich? *.* ähnelt.
        /// </summary>
        public static string Really {
            get {
                return ResourceManager.GetString("Really", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die entfernen ähnelt.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen Suchen ähnelt.
        /// </summary>
        public static string SearchLessons {
            get {
                return ResourceManager.GetString("SearchLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Satz ähnelt.
        /// </summary>
        public static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld darf nicht leer sein! ähnelt.
        /// </summary>
        public static string SentenceTextboxCantBeEmpty {
            get {
                return ResourceManager.GetString("SentenceTextboxCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen auswählen ähnelt.
        /// </summary>
        public static string SetLessons {
            get {
                return ResourceManager.GetString("SetLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ zuweisen ähnelt.
        /// </summary>
        public static string SetType {
            get {
                return ResourceManager.GetString("SetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Lücken für den Lückentext fehlen! ähnelt.
        /// </summary>
        public static string SomeInsertPartsAreMissing {
            get {
                return ResourceManager.GetString("SomeInsertPartsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersetzung ähnelt.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen hochladen ähnelt.
        /// </summary>
        public static string UploadLesson {
            get {
                return ResourceManager.GetString("UploadLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vokabel-Lektionen ähnelt.
        /// </summary>
        public static string VocabLesson {
            get {
                return ResourceManager.GetString("VocabLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kana- und Übersetztung-Textboxen dürfen nicht leer sein! ähnelt.
        /// </summary>
        public static string VocabTextboxesCantBeEmpty {
            get {
                return ResourceManager.GetString("VocabTextboxesCantBeEmpty", resourceCulture);
            }
        }
    }
}
