//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihongoSenpai.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NihongoSenpai.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhalt hinzufügen ähnelt.
        /// </summary>
        public static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adverb ähnelt.
        /// </summary>
        public static string Adv {
            get {
                return ResourceManager.GetString("Adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adverben ähnelt.
        /// </summary>
        public static string Advs {
            get {
                return ResourceManager.GetString("Advs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nochmal??? *_* ähnelt.
        /// </summary>
        public static string Again {
            get {
                return ResourceManager.GetString("Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fast Richtig ähnelt.
        /// </summary>
        public static string AlmostCorrect {
            get {
                return ResourceManager.GetString("AlmostCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nihongo Senpai ツ ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach Lektion ähnelt.
        /// </summary>
        public static string ByLesson {
            get {
                return ResourceManager.GetString("ByLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übung Abbrechen ähnelt.
        /// </summary>
        public static string CancelExercise {
            get {
                return ResourceManager.GetString("CancelExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ändern ähnelt.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Richtig ähnelt.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Richtig, schwer zu merken ähnelt.
        /// </summary>
        public static string CorrectDifficult {
            get {
                return ResourceManager.GetString("CorrectDifficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Richtig, mit Zögern ähnelt.
        /// </summary>
        public static string CorrectWithHasitate {
            get {
                return ResourceManager.GetString("CorrectWithHasitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Richtig/Falsch Relation:  ähnelt.
        /// </summary>
        public static string CorrectWrongRelation {
            get {
                return ResourceManager.GetString("CorrectWrongRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Source=isostore:/SenpaiDatabase.sdf ähnelt.
        /// </summary>
        public static string DatabaseConnectionString {
            get {
                return ResourceManager.GetString("DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank zurückgesetzt. ähnelt.
        /// </summary>
        public static string DatabaseReseted {
            get {
                return ResourceManager.GetString("DatabaseReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beispiel ähnelt.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortschritt sichern ähnelt.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vergessen ähnelt.
        /// </summary>
        public static string Forgotten {
            get {
                return ResourceManager.GetString("Forgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die de-&gt;jap ähnelt.
        /// </summary>
        public static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch -&gt; Japanisch ähnelt.
        /// </summary>
        public static string GermanJapanese {
            get {
                return ResourceManager.GetString("GermanJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die い-Adjektiv ähnelt.
        /// </summary>
        public static string iAdj {
            get {
                return ResourceManager.GetString("iAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die い-Adjektive ähnelt.
        /// </summary>
        public static string iAdjs {
            get {
                return ResourceManager.GetString("iAdjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortschrit wiederherstellen ähnelt.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die jap-&gt;de ähnelt.
        /// </summary>
        public static string jap {
            get {
                return ResourceManager.GetString("jap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Japanisch -&gt; Deutsch ähnelt.
        /// </summary>
        public static string JapaneseGerman {
            get {
                return ResourceManager.GetString("JapaneseGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die jap&lt;-&gt;de ähnelt.
        /// </summary>
        public static string japGer {
            get {
                return ResourceManager.GetString("japGer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kana ähnelt.
        /// </summary>
        public static string Kana {
            get {
                return ResourceManager.GetString("Kana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanji ähnelt.
        /// </summary>
        public static string Kanji {
            get {
                return ResourceManager.GetString("Kanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kunyomi ähnelt.
        /// </summary>
        public static string Kunyomi {
            get {
                return ResourceManager.GetString("Kunyomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter zusammensetzen ähnelt.
        /// </summary>
        public static string LearnCombine {
            get {
                return ResourceManager.GetString("LearnCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter konjugieren ähnelt.
        /// </summary>
        public static string LearnConjugation {
            get {
                return ResourceManager.GetString("LearnConjugation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lernrichtung: ähnelt.
        /// </summary>
        public static string LearnDirection {
            get {
                return ResourceManager.GetString("LearnDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanji Flashcards ähnelt.
        /// </summary>
        public static string LearnFlashcards {
            get {
                return ResourceManager.GetString("LearnFlashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partikel einsetzen ähnelt.
        /// </summary>
        public static string LearnInsert {
            get {
                return ResourceManager.GetString("LearnInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lernmodus ähnelt.
        /// </summary>
        public static string LearnMode {
            get {
                return ResourceManager.GetString("LearnMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vokabeln lernen ähnelt.
        /// </summary>
        public static string LearnVocab {
            get {
                return ResourceManager.GetString("LearnVocab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsche Wörter lernen ähnelt.
        /// </summary>
        public static string LearnWrongWords {
            get {
                return ResourceManager.GetString("LearnWrongWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsche Wörter Zeitnah wiederholen ähnelt.
        /// </summary>
        public static string LearnWrongWordsInTime {
            get {
                return ResourceManager.GetString("LearnWrongWordsInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Wörter laden ähnelt.
        /// </summary>
        public static string LoadAll {
            get {
                return ResourceManager.GetString("LoadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Kanji laden ähnelt.
        /// </summary>
        public static string LoadAllKanji {
            get {
                return ResourceManager.GetString("LoadAllKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Am längsten nicht gelernt ähnelt.
        /// </summary>
        public static string LongestNotLearned {
            get {
                return ResourceManager.GetString("LongestNotLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übungen ähnelt.
        /// </summary>
        public static string MenuExercises {
            get {
                return ResourceManager.GetString("MenuExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erklärungen ähnelt.
        /// </summary>
        public static string MenuExplanations {
            get {
                return ResourceManager.GetString("MenuExplanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sonstiges ähnelt.
        /// </summary>
        public static string MenuOthers {
            get {
                return ResourceManager.GetString("MenuOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter mindestens gelernt:  ähnelt.
        /// </summary>
        public static string MinWordsCount {
            get {
                return ResourceManager.GetString("MinWordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modus:  ähnelt.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Am meisten falsch zuerst ähnelt.
        /// </summary>
        public static string MostWrong {
            get {
                return ResourceManager.GetString("MostWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die な-Adjektiv ähnelt.
        /// </summary>
        public static string naAdj {
            get {
                return ResourceManager.GetString("naAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die な-Adjektive ähnelt.
        /// </summary>
        public static string naAdjs {
            get {
                return ResourceManager.GetString("naAdjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Kanji pro Runde: ähnelt.
        /// </summary>
        public static string NewKanjiPerRound {
            get {
                return ResourceManager.GetString("NewKanjiPerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Wörter pro Runde:  ähnelt.
        /// </summary>
        public static string NewWordsPerRound {
            get {
                return ResourceManager.GetString("NewWordsPerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Kanji in den gewählten Lektionen mehr verfügbar! ähnelt.
        /// </summary>
        public static string NoKanjisLeft {
            get {
                return ResourceManager.GetString("NoKanjisLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Lektion Ausgewählt! ähnelt.
        /// </summary>
        public static string NoLessonSelected {
            get {
                return ResourceManager.GetString("NoLessonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nomen ähnelt.
        /// </summary>
        public static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Wort ausgewählt! ähnelt.
        /// </summary>
        public static string NoWordSelected {
            get {
                return ResourceManager.GetString("NoWordSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Wörter in den gewählten Lektionen mehr verfügbar! ähnelt.
        /// </summary>
        public static string NoWordsLeft {
            get {
                return ResourceManager.GetString("NoWordsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Onyomi ähnelt.
        /// </summary>
        public static string Onyomi {
            get {
                return ResourceManager.GetString("Onyomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sonstige ähnelt.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partikel ähnelt.
        /// </summary>
        public static string Particle {
            get {
                return ResourceManager.GetString("Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phrase ähnelt.
        /// </summary>
        public static string Phr {
            get {
                return ResourceManager.GetString("Phr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phrasen ähnelt.
        /// </summary>
        public static string Phrs {
            get {
                return ResourceManager.GetString("Phrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präfix ähnelt.
        /// </summary>
        public static string Pref {
            get {
                return ResourceManager.GetString("Pref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präffixe ähnelt.
        /// </summary>
        public static string Prefs {
            get {
                return ResourceManager.GetString("Prefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zufällig ähnelt.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl ähnelt.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl Optionen: ähnelt.
        /// </summary>
        public static string RangeOptions {
            get {
                return ResourceManager.GetString("RangeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wirklich? *.* ähnelt.
        /// </summary>
        public static string Really {
            get {
                return ResourceManager.GetString("Really", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsche Wörter wiederholen nach  ähnelt.
        /// </summary>
        public static string RepeatAfter {
            get {
                return ResourceManager.GetString("RepeatAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank zurücksetzen ähnelt.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die de-DE ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runde beendet ähnelt.
        /// </summary>
        public static string RoundFinished {
            get {
                return ResourceManager.GetString("RoundFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesuchtes Wort ähnelt.
        /// </summary>
        public static string SearchedWord {
            get {
                return ResourceManager.GetString("SearchedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter suchen ähnelt.
        /// </summary>
        public static string SearchWords {
            get {
                return ResourceManager.GetString("SearchWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles auswählen ähnelt.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergrund auswählen ähnelt.
        /// </summary>
        public static string SelectBackground {
            get {
                return ResourceManager.GetString("SelectBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lektionen abwählen ähnelt.
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzeigen ähnelt.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Immer Anzeigen ähnelt.
        /// </summary>
        public static string ShowAlways {
            get {
                return ResourceManager.GetString("ShowAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung Anzeigen: ähnelt.
        /// </summary>
        public static string ShowDescription {
            get {
                return ResourceManager.GetString("ShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibungen Anzeigen ähnelt.
        /// </summary>
        public static string ShowDescriptions {
            get {
                return ResourceManager.GetString("ShowDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei deutschem Wort anz. ähnelt.
        /// </summary>
        public static string ShowGerman {
            get {
                return ResourceManager.GetString("ShowGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grammatik anzeigen ähnelt.
        /// </summary>
        public static string ShowGrammar {
            get {
                return ResourceManager.GetString("ShowGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei japanischem Wort anz. ähnelt.
        /// </summary>
        public static string ShowJap {
            get {
                return ResourceManager.GetString("ShowJap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur Deutsches Wort anzeigen ähnelt.
        /// </summary>
        public static string ShowJustGerman {
            get {
                return ResourceManager.GetString("ShowJustGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur Japanisches Wort anzeigen ähnelt.
        /// </summary>
        public static string ShowJustJap {
            get {
                return ResourceManager.GetString("ShowJustJap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanjis anzeigen ähnelt.
        /// </summary>
        public static string ShowKanji {
            get {
                return ResourceManager.GetString("ShowKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nie anzeigen ähnelt.
        /// </summary>
        public static string ShowNever {
            get {
                return ResourceManager.GetString("ShowNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wort anzeigen: ähnelt.
        /// </summary>
        public static string ShowWord {
            get {
                return ResourceManager.GetString("ShowWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter anzeigen ähnelt.
        /// </summary>
        public static string ShowWords {
            get {
                return ResourceManager.GetString("ShowWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sortieren nach: ähnelt.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suffix ähnelt.
        /// </summary>
        public static string Suff {
            get {
                return ResourceManager.GetString("Suff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suffixe ähnelt.
        /// </summary>
        public static string Suffs {
            get {
                return ResourceManager.GetString("Suffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supermemo ähnelt.
        /// </summary>
        public static string Supermemo {
            get {
                return ResourceManager.GetString("Supermemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zum anzeigen hier tippen ähnelt.
        /// </summary>
        public static string TapToShow {
            get {
                return ResourceManager.GetString("TapToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersetzung ähnelt.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ: ähnelt.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die う-Verb ähnelt.
        /// </summary>
        public static string Verb1 {
            get {
                return ResourceManager.GetString("Verb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die る-Verb ähnelt.
        /// </summary>
        public static string Verb2 {
            get {
                return ResourceManager.GetString("Verb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die irreguläres Verb ähnelt.
        /// </summary>
        public static string Verb3 {
            get {
                return ResourceManager.GetString("Verb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die う-Verben ähnelt.
        /// </summary>
        public static string Verbs1 {
            get {
                return ResourceManager.GetString("Verbs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die る-Verben ähnelt.
        /// </summary>
        public static string Verbs2 {
            get {
                return ResourceManager.GetString("Verbs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die irreguläre Verben ähnelt.
        /// </summary>
        public static string Verbs3 {
            get {
                return ResourceManager.GetString("Verbs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Wörtern ähnelt.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Richtig:  ähnelt.
        /// </summary>
        public static string WordsCorrect {
            get {
                return ResourceManager.GetString("WordsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbleibend:  ähnelt.
        /// </summary>
        public static string WordsLeft {
            get {
                return ResourceManager.GetString("WordsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsch:  ähnelt.
        /// </summary>
        public static string WordsWrong {
            get {
                return ResourceManager.GetString("WordsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsch ähnelt.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsch, aber geht noch ähnelt.
        /// </summary>
        public static string WrongButOk {
            get {
                return ResourceManager.GetString("WrongButOk", resourceCulture);
            }
        }
    }
}
